name: Docker

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-docker-action@main
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
